### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by Suleman-Elahi** [coenjacobs/wp-haveibeenpwned#2]
Warning: require(vendor/autoload_52.php): failed to open stream: No such file or directory in /mnt/data/vhosts/casite-777739.cloudaccess.net/httpdocs/wp-content/plugins/wp-haveibeenpwned-0.1.0/wp-haveibeenpwned.php on line 11

Warning: require(vendor/autoload_52.php): failed to open stream: No such file or directory in /mnt/data/vhosts/casite-777739.cloudaccess.net/httpdocs/wp-content/plugins/wp-haveibeenpwned-0.1.0/wp-haveibeenpwned.php on line 11

Fatal error: require(): Failed opening required 'vendor/autoload_52.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /mnt/data/vhosts/casite-777739.cloudaccess.net/httpdocs/wp-content/plugins/wp-haveibeenpwned-0.1.0/wp-haveibeenpwned.php on line 11

**Comment by E-VANCE** [comment]
Same here...

**Comment by coenjacobs** [comment]
Please run `composer install` in the directory you have downloaded, to setup dependencies and the autoloader (which is the missing file in the error) before you use this plugin.
